name: foodibizz
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  auto_route: ^7.7.0
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  dio_smart_retry: ^5.0.0
  dotted_border: ^2.0.0+3
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.0.4
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.7
  fluttertoast: ^8.2.1
  google_fonts: ^5.1.0
  hive_flutter: ^1.1.0
  image_cropper: ^5.0.0
  image_picker: ^1.0.4
  intl: any
  multiple_result: ^5.1.0
  responsive_framework: ^1.1.0
  talker_dio_logger: ^2.1.2
  talker_flutter: ^3.1.5
  google_fonts: ^5.1.0
  dio: ^5.3.2
  dio_smart_retry: ^5.0.0
  fluttertoast: ^8.2.1
  multiple_result: ^5.1.0
  cached_network_image: ^3.2.3
  dotted_border: ^2.0.0+3
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  flutter_image_compress: ^2.0.4
  flutter_slidable: ^3.0.0

dev_dependencies:
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.6
  custom_lint: ^0.4.0
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  riverpod_lint: ^1.3.2
  riverpod_test: ^0.1.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
